name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform
        id: plan
        run: terraform plan -out=tfplan

      - name: Apply Terraform
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan

      - name: Get Terraform Outputs
        id: outputs
        run: |
          terraform output -json > output.json
          echo "db_instance_1_endpoint=$(jq -r .db_instance_1_endpoint.value output.json)" >> $GITHUB_ENV
          echo "db_instance_2_endpoint=$(jq -r .db_instance_2_endpoint.value output.json)" >> $GITHUB_ENV

      - name: Print Terraform Outputs
        run: |
          echo "DB Instance 1 Endpoint: ${{ env.db_instance_1_endpoint }}"
          echo "DB Instance 2 Endpoint: ${{ env.db_instance_2_endpoint }}"
